### ISSUE TITLE
Sometimes it doesnt recognize a person at all.

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#10]
Keeps throwing "Fake"/"Stranger" even for a person with 3 photographs.
While sometimes it works. This happened when we took the photo in the same room, we tested this application for.
I cant understand why this erratic behavior, is it due to lightening of room or anything else

**Comment by Qengineering** [comment]
This behavior is hard to overcome. Please use the command line input when adding a face to the collection `$ ./main -MyNewFace.jpg` The picture is going to be processed as being taken 'live' with the camera. Manually putting pictures in the database is not advised. The needed warp projection isn't applied in this case.

Second possible reason can be the moment the picture is taken. Using auto fill will place a picture in the database at the moment it's considered to be correct. Not too much blur, and facing the camera more or less. Please take a look in the database to see if all the faces are sharp and facing the camera in front.

**Comment by rsingh2083** [comment]
I didnt put images manually. I took snapshot of three images of a person and renamed them as p1.jpg, p1#1.jpg, p2#2.jpg 
and then ran ./Facerecognition -p1.jpg (...etc)
The problem with autofill is that its populating some blurry and choppy images also

**Comment by Qengineering** [comment]
As far as I can see, you did the correct thing.  Running ./Facerecognition p1.jpg will load only p1 in the database. You can check if the warp projection is performed on the face by comparing the original and the one in the database. Most times the face in the database will be 'wider'.

**Comment by rsingh2083** [comment]
Your readme mentions that RetinaFace is more accurate and input is 324x240. But when I add image to database using Retina enabled FaceRecognition, then also the size of images in database are 112x112 pixels only.

**Comment by Qengineering** [comment]
There are a few deep learning models working here.

RetinaFace to recognize a face in a scene, or
MtCNN to recognize a face in a scene.
Live is trying to determine if a person is live or some photo of a face.
Mask, to see if a person is wearing a mask.
MobileFaceNet to do the actual recognition of a person from the database.

Each model has it's unique input size. 
In this case uses RetinaFace 324x240, whilst MobileFaceNet works with cropped faces of 112x112.
