### ISSUE TITLE
Whats the difference between a stranger and a person 

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#16]
Hi Sir,

The code auto-assigns number to each and every person (person10, person 12 etc).
Then whats the logic behind calling someone a stranger ?

**Comment by Qengineering** [comment]
With a fixed collection of faces, it is important to check whether a person belongs in or outside the set. For example, a class with 25 students. At the beginning of the new trimester, you fill the database with their faces. You don't allow extending the database (AUTO_FILL_DATABASE = OFF).
Now, when a person enters the room, you are given a number (valid) or stranger (not seen before, not valid).
