### ISSUE TITLE
How to deal with 3800 face records 

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#3]
Sir my college has approx 3800 students and some 500 in staff. Will nano be able to handle this much load or shall we test on Jetson Xavier. Or if you can then please suggest an alternative hardware as we are not in college premise right now, but after two months we would like to demo this at our college by being well prepared in advance.

**Comment by Qengineering** [comment]
Two points.
The limit on the number of recognizable faces comes down to the arcface deep learning model. They claim that 3800 faces are no problem, but I've never tested it. No need here for expensive hardware.

Within a week or so, I will publish a new face mask detection app, working with TensorFlow Lite. It will be capable of detecting black or colored masks also.
