### ISSUE TITLE
RetinaFace crashing at stage 8 when Release mode but all is working DEBUG mode ?

### ISSUE THREAD

**Issue by MyraBaba** [Qengineering/Face-Recognition-with-Mask-Jetson-Nano#5]
Hi @Qengineering 

Program working DEBUG mode but crashing at Release mode... 

Retina face is crashing..

really strange..

**Comment by MyraBaba** [comment]
@Qengineering 

I tried this with raspberry pi 4 4 its crashing RELEASE mode. Same code working my i9 ubuntu 20 desktop linux both Relese and debug.

FYI

**Comment by Qengineering** [comment]
Fixed bug in TBlur.cpp causing NAN output.
![image](https://user-images.githubusercontent.com/44409029/108069339-8d528200-7063-11eb-9f8f-f41ae45bc47b.png)
